name: Latest blog post workflow
on: 
    schedule:
        - cron: '0 * * * *'
    workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  actions: write
  
jobs: 
    update-readme-with-blog: 
        name: Update this repo's README with latest blog posts
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                token: ${{ secrets.PAT_TOKEN }}
              
            - name: Pull in medium posts
              uses: gautamkrishnar/blog-post-workflow@master
              with: 
                max_post_count: "4"
                feed_list: "https://gauranshmathur.site"
                committer_username: "github-actions[bot]"
                committer_email: "github-actions[bot]@users.noreply.github.com"
                gh_token: ${{ secrets.PAT_TOKEN }}
